[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
via-ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@crytic/=node_modules/@crytic/",
    "@ensdomains/=node_modules/@ensdomains/",
    "@ethereum-waffle/=node_modules/@ethereum-waffle/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@chimera/=node_modules/chimera/src",
    "ds-test/=node_modules/chimera/lib/forge-std/lib/ds-test/",
    "forge-std/=lib/forge-std/src",
    "hardhat/=node_modules/hardhat/",
    "solmate/=node_modules/solmate/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
